stages:
  - build
  - deploy

build-image:
    stage: build
    image: docker
    services:
      - name: docker:dind
        alias: docker

    variables:
      DOCKER_HOST: tcp://docker:2375
      DOCKER_TLS_CERTDIR: ""

    script:
      - docker build -t frontend .
      - docker tag frontend $HarborRepo/$HrProject/frontend:latest
      - echo "$HrPasswd" | docker login $HarborRepo -u $username --password-stdin
      - docker push $HarborRepo/$HrProject/frontend

# deploy:
#     stage: deploy
#     script:
#         - echo "Deploying..."
#         - docker -v