FROM node:20 AS build

WORKDIR /app
COPY *.json /app/
RUN npm install

COPY . .
RUN npm run build

FROM nginx:alpine AS prod
COPY --from=Build /app/dist /var/www/html/
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]