FROM node:20 AS build

WORKDIR /app
COPY *.json /app/
RUN npm install

COPY . .
RUN npm run build

FROM nginx:alpine AS prod
COPY --from=build /app/dist /var/www/html/
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY docker-entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

EXPOSE 80

ENTRYPOINT ["/entrypoint.sh"]
CMD ["nginx", "-g", "daemon off;"]